INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:Client ������� ������ ���������� status updated by: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Client deleted by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Client  data updated by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Client  data updated by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Added new client New Client by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Added new service NEW by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Service deleted by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Added new role user by: admin
WARNING:root:Insert role raised error: syntax error at or near "user"
LINE 1: CREATE ROLE user WITH LOGIN PASSWORD 'user' IN GROUP manager...
                    ^
QUERY:  CREATE ROLE user WITH LOGIN PASSWORD 'user' IN GROUP managers
CONTEXT:  PL/pgSQL function add_user(character varying,character varying) line 3 at EXECUTE

INFO:root:Established new connection to database by admin.
WARNING:root:Added new role newuser by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by newuser.
INFO:root:User login: newuser
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\routing.py", line 189, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\routing.py", line 137, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "restlin.py", line 66, in log_in
    response = Response()
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Response
services
  field required (type=value_error.missing)
data
  field required (type=value_error.missing)
INFO:root:Established new connection to database by vlado.
ERROR:root:Get data for managers raised error: 5 validation errors for Data
name
  field required (type=value_error.missing)
phone
  field required (type=value_error.missing)
adress
  field required (type=value_error.missing)
salary
  field required (type=value_error.missing)
statuses
  field required (type=value_error.missing)
ERROR:root:Exception raised in post route /user: local variable 'response' referenced before assignment
INFO:root:User login: vlado
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\routing.py", line 205, in app
    is_coroutine=is_coroutine,
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\routing.py", line 124, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\encoders.py", line 147, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\encoders.py", line 147, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\encoders.py", line 94, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\encoders.py", line 94, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "C:\dev\BD-5th-sem\venv\lib\site-packages\fastapi\encoders.py", line 139, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'ModelField' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO:root:Established new connection to database by vlado.
ERROR:root:Get data for managers raised error: 5 validation errors for Data
name
  field required (type=value_error.missing)
phone
  field required (type=value_error.missing)
adress
  field required (type=value_error.missing)
salary
  field required (type=value_error.missing)
statuses
  field required (type=value_error.missing)
ERROR:root:Exception raised in post route /user: local variable 'response' referenced before assignment
INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
ERROR:root:Get data for managers raised error: 5 validation errors for Data
name
  field required (type=value_error.missing)
phone
  field required (type=value_error.missing)
adress
  field required (type=value_error.missing)
salary
  field required (type=value_error.missing)
statuses
  field required (type=value_error.missing)
ERROR:root:Exception raised in post route /user: local variable 'response' referenced before assignment
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
ERROR:root:Get data for managers raised error: 5 validation errors for Data
name
  field required (type=value_error.missing)
phone
  field required (type=value_error.missing)
adress
  field required (type=value_error.missing)
salary
  field required (type=value_error.missing)
statuses
  field required (type=value_error.missing)
ERROR:root:Exception raised in post route /user: local variable 'response' referenced before assignment
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Client  data updated by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Added new client �� by: admin
ERROR:root:Insert client raised error: insert or update on table "live" violates foreign key constraint "fk_service"
DETAIL:  Key (service_id)=(1) is not present in table "services".
CONTEXT:  SQL statement "INSERT INTO live VALUES(NEW.id, i, (SELECT id FROM statuses WHERE status LIKE 'call back'))"
PL/pgSQL function on_insert_clients() line 4 at SQL statement
SQL statement "INSERT INTO clients (fio, tel, job, homeadress, salary, call_back) VALUES (fio_p, tel_p, job_p, homeadress_p, salary_p, true)"
PL/pgSQL function insert_client(character varying,character varying,character varying,character varying,numeric) line 3 at SQL statement

INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
ERROR:root:Get data for managers raised error: list index out of range
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Service deleted by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Added new client New by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by vlado.
ERROR:root:Get data for managers raised error: list index out of range
INFO:root:User login: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Service deleted by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Added new service NEW by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Added new client NewClient by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:Client ������� ������ ���������� status updated by: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Service deleted by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Added new service ONE by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Added new role newuser by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Role deleted by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Role deleted by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Role deleted by: admin
INFO:root:Established new connection to database by admin.
ERROR:root:Exception raised in post route /user: FATAL:  password authentication failed for user "vlado"

INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
WARNING:root:Added new role vlado by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:Client ��������� ����� ���������� status updated by: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Client  data updated by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Client  data updated by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:User login: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
INFO:root:Client  data updated by: admin
INFO:root:Established new connection to database by admin.
INFO:root:Established new connection to database by admin.
ERROR:root:Exception raised in post route /user: 'Database' object has no attribute '_Database__CONNECTION'
INFO:root:User login: vlado
INFO:root:Established new connection to database by vlado.
INFO:root:User login: vlado
